### ISSUE TITLE
facing a install error -  'boost/python.hpp' file not found

### ISSUE THREAD

**Issue by MaBecker** [matthewelse/pygattosx#3]
Hi,

running on Mac Os X Sierra 10.12.1

python --version
Python 2.7.10

**looks like my system is missing some include files - any hints ?**

sudo python setup.py install
.....
Running pyxpcconnection-master/setup.py -q bdist_egg --dist-dir /tmp/easy_install-0HHUfT/pyxpcconnection-master/egg-dist-tmp-AQF3Ys
In file included from src/XpcConnectionBase.cpp:21:
src/XpcConnectionBase.h:18:10: fatal error: 'boost/python.hpp' file not found
#include <boost/python.hpp>
         ^
1 error generated.
error: Setup script exited with error: command 'cc' failed with exit status 1

**Comment by matthewelse** [comment]
Hi,

Have you installed boost-Python? You should be able to install it with brew:

brew install boost-python

**Comment by MaBecker** [comment]
ok - installed boost-python.

same error 

anything else I have to install ?

**Comment by gaoyangyiqiao** [comment]
How did you solve this problem? Met the same error

**Comment by MaBecker** [comment]
Have not found a solution to fix this ....

**Comment by Headmaster11** [comment]
Maybe anyone have found a solution after 5 years

**Comment by matthewelse** [comment]
Not sure whether you actually want this library, if you just want a BLE library, I made some changes to [matthewelse/bleep](https://github.com/matthewelse/bleep) recently which should be much less flakey.
